### ISSUE TITLE
Error "Schema must be an instance of GraphQLSchema" in pad

### ISSUE THREAD

**Issue by almilo** [apollographql/launchpad#72]
Hi guys,

In this pad: https://launchpad.graphql.com/1xlk994v9 I get a "Schema must be an instance of GraphQLSchema" error. GraphQL is a peer dependency of the library I am using (see https://github.com/almilo/graphql-needle/blob/master/package.json#L45).
The exported schema is asynchronous (stitched) so 'makeAnnotatedExecutableSchema()' returns a promise. Any idea what can be wrong?

This example works without issues on node 6.10.0:
```javascript
// package.json
{
  "name": "graphql-needle-test",
  "version": "1.0.0",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "graphql": "0.11.7",
    "graphql-needle": "^0.0.9"
  }
}

// index.js
const {graphql} = require('graphql');
const {makeAnnotatedExecutableSchema} = require('graphql-needle');

const authorSchemaUri = 'https://8xz15vx5q.lp.gql.zone/graphql'; // Apollo Launchpad https://launchpad.graphql.com/vpzl4vxr3
const chirpSchemaUri = 'https://vpzl4vxr3.lp.gql.zone/graphql'; // Apollo Launchpad https://launchpad.graphql.com/8xz15vx5q
const annotatedSchema = `
    extend type User @schema(uri: "${authorSchemaUri}") {
      chirps: [Chirp] @stitch(keyField: "id", queryField: "chirpsByAuthorId", queryParameter: "authorId")
    }
    extend type Chirp @schema(uri: "${chirpSchemaUri}") {
      author: User @stitch(keyField: "authorId", queryField: "userById", queryParameter: "id")
    }
`;

makeAnnotatedExecutableSchema(annotatedSchema).then(schema => {
    const query = `
            query {
              userById(id: "fakeChirpId") {
                email
                chirps { 
                    text
                }
              }
            }
        `;

    graphql(schema, query).then(({data}) => console.log(data));
});
```
Thanks in advance,
Alberto

**Comment by stubailo** [comment]
Hi! We're aware of the issue and working on a fix. Thanks for reporting!

**Comment by stubailo** [comment]
Fixed!

**Comment by n1ru4l** [comment]
@stubailo I am still having the problem. The launchpad posted by @almilo is not working and also this one is also not working: https://launchpad.graphql.com/0l3x1v4p5
